#!/usr/bin/env bash

sudo yum install -y epel-release
sudo yum install -y nginx

# disable selinux nginx reverseproxy required
sudo sed -i 's\=enforcing\=disabled\g' /etc/sysconfig/selinux

sudo sestatus 

sudo setenforce 0 

sudo sestatus 

sudo echo '
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;
}' | sudo tee /etc/nginx/nginx.conf

sudo echo '
server {

  listen	80 default;
  server_name 	jenkins.local;

  access_log    /var/log/nginx/jenkins.access.log;
  error_log     /var/log/nginx/jenkins.error.log;

  proxy_buffers 16 64k;
  proxy_buffer_size 128k;

  location / {
      proxy_pass http://127.0.0.1:8080;
      proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
      proxy_redirect off;

      proxy_set_header	Host		$host;
      proxy_set_header  X-Real-IP	$remote_addr;
      proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header  X-Forwarded-Proto http;
  }

}' | sudo tee /etc/nginx/conf.d/jenkins.conf
sudo systemctl enable jenkins
sudo systemctl restart jenkins
sudo systemctl restart nginx

sudo cat /var/lib/jenkins/secrets/initialAdminPassword
sudo hostname --ip-address
